#!/bin/bash

clear

rm *private*
rm *mtm_tot*

gcc -std=c99 -Wall -pedantic-errors -Werror -DNDEBUG part1.c -o mtm_tot

./mtm_tot < test1.in > test1_private.out
./mtm_tot < test2.in > test2_private.out
./mtm_tot < test3.in > test3_private.out
./mtm_tot < test4.in > test4_private.out

valgrind --leak-check=yes ./mtm_tot < test1.in
valgrind --leak-check=yes ./mtm_tot < test2.in
valgrind --leak-check=yes ./mtm_tot < test3.in
valgrind --leak-check=yes ./mtm_tot < test4.in

