#!/bin/bash

clear

gcc -std=c99 -Wall -pedantic-errors -Werror -DNDEBUG -g ./mtm_map/map.c ./tests/chessSystemTestsExample.c ./chessSystem.c -o chessSystemTestsExample

valgrind --leak-check=full ./chessSystemTestsExample > output 2>&1

