#!/bin/bash

clear

gcc -std=c99 -Wall -pedantic-errors -Werror -DNDEBUG -g ./mtm_map/map.c ./tests/map_example_test.c -o map_example_test

valgrind --leak-check=full ./map_example_test > outpput 2>&1

